---
title: "Knitr Parameters"
author: "John Mount"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
params:
  FN: sin
  VAR: east
  title: "user chosen function plot"
vignette: >
  %\VignetteIndexEntry{Knitr Parameters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

An idea of [Jason Becker](http://jsonbecker.com)'s: using `replyr::let` with `knitr` passed parameters.

## Bindings

You can use the `knitr` parameters in `replyr::let` blocks.

```{r bindings}
library("replyr")
print(params)

east = 7
let(
  alias=restrictToNameAssignments(params),
  expr={ 
    print(paste(quote(VAR),VAR))
    plot(FN(0.1*(1:20)))
    title(params$title)
  })
```

## Values

Or, assuming everything you do is only standard evaluation and you don't care about capturing variable names: you can capture references to values once and have all subsequent blocks use those values.

```{r values}
FN <- let(restrictToNameAssignments(params), FN)

plot(FN(0.1*(1:20)))
title(params$title)
```
