---
title: "sqllite Example"
author: "John Mount"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sqllite Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = " # "
)
options(width =100)
```

Example trying `replyr` functions on a sqlite data source.

```{r setup}
library('dplyr')
```

First we run the examples on `data.frame`s.

```{r dataframeexamples}
d1 <- data.frame(x=c(1,2),y=c('a','b'))

d1 %>% replyr::replyr_colClasses()
d1 %>% replyr::replyr_testCols(is.numeric)

d1 %>% replyr::replyr_dim()

d1 %>% replyr::replyr_nrow()

d1 %>% replyr::replyr_str()

d2 <- data.frame(x=c(1,2,3),y=c(3,5,NA),z=c('a',NA,'z'))

d2 %>% replyr::replyr_quantile('x')

d2 %>% replyr::replyr_summary()

d3 <- data.frame(x=c('a','a','b','b','c','c'),
                 y=1:6,
                 stringsAsFactors=FALSE)
values <- c('a','c')

d3 %>% replyr::replyr_filter('x',values)

d3 %>% replyr::replyr_inTest('x',values,'match')

d4 <- data.frame(x=c(1,2,3,3))

d4 %>% replyr::replyr_uniqueValues('x')
```



Then we run the same examples on DB backed stores.  Notice in some cases types and row-order changes, but we can run the same commands.

```{r dbexamples}
if(requireNamespace('RSQLite')) {
  my_db <- dplyr::src_sqlite("replyr_sqliteEx.sqlite3", create = TRUE)
  
  d1 <- copy_to(my_db,data.frame(x=c(1,2),y=c('a','b')),'d1')
  
  print(d1 %>% replyr::replyr_colClasses())
  print(d1 %>% replyr::replyr_testCols(is.numeric))
  
  print(d1 %>% replyr::replyr_dim())
  
  print(d1 %>% replyr::replyr_nrow())
  
  print(d1 %>% replyr::replyr_str())
  
  # mysql crashes on copy_to with NA values in string constants
  # https://github.com/hadley/dplyr/issues/2259
  #  and sparklyr converts them to space anyway.
  d2 <- copy_to(my_db,data.frame(x=c(1,2,3),y=c(3,5,NA),z=c('a','a','z')),'d2')
  
  print(d2 %>% replyr::replyr_quantile('x'))
  
  print(d2 %>% replyr::replyr_summary())
  
  
  d2b <- copy_to(my_db,data.frame(x=c(1,2,3),y=c(3,5,NA),z=c('a','a','z'),
                                  stringsAsFactors = FALSE),'d2b')
  
  print(d2b %>% replyr::replyr_quantile('x'))
  
  print(d2b %>% replyr::replyr_summary())
  
  d3 <- copy_to(my_db,data.frame(x=c('a','a','b','b','c','c'),
                                 y=1:6,
                                 stringsAsFactors=FALSE),'d3')
  ## dplyr::sample_n(d3,3) # not currently implemented for tbl_sqlite
  
  values <- c('a','c')
  
  print(d3 %>% replyr::replyr_filter('x',values,verbose=FALSE))
  
  print(d3 %>% replyr::replyr_inTest('x',values,'match',verbose=FALSE))
  
  print(d4 <- copy_to(my_db, data.frame(x=c(1,2,3,3)),'d4'))
  
  print(d4 %>% replyr::replyr_uniqueValues('x'))
}
```
