---
title: "summary"
author: "John Mount"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{summary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = " # "
)
options(width =100)
```

`replyr_summary` example.

`replyr_summary` works on various data sources, counts <code>NA</code>, and returns a <code>data.frame</code> (instead of text).
 
 
```{r example}

d <- data.frame(x=c(NA,'b'), y=c(1,NA), stringsAsFactors= FALSE)

summary(d)

replyr::replyr_summary(d)

execute_vignette <- requireNamespace("RSQLite", quietly = TRUE) &&
  requireNamespace("dbplyr", quietly = TRUE)
if(execute_vignette) {
  my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  RSQLite::initExtension(my_db)
  dbData <- dplyr::copy_to(my_db, d)
  
  summary(dbData)
  
  replyr::replyr_summary(dbData)
  
  # glimpse works more like str or head
  dplyr::glimpse(dbData)
}

```

```{r cleanup}
DBI::dbDisconnect(my_db)
rm(list=ls())
gc()
```