---
output:
  md_document:
    variant: markdown_github
---

### binding rows on spark

It would be nice if `dplyr::bind_rows` could be a used on `Sparklyr` data handles.

<!-- Generated from .Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = " # "
)
options(width =100)
```


OSX 10.11.6.
Spark installed as described at http://spark.rstudio.com

```
library('sparklyr')
spark_install(version = "2.0.0")
```

```{r setup}
library('dplyr')
library('sparklyr')
R.Version()$version.string
packageVersion('dplyr')
packageVersion('sparklyr')
my_db <- sparklyr::spark_connect(version='2.0.0', master = "local")
class(my_db)
my_db$spark_home
print(my_db)
```

 * Expected outcome: dplyr::bind_rows to work with `Sparklyr` data reference.
 * Observed outcome: can't bind.

```{r issue, error=TRUE}
support <- copy_to(my_db,
                   data.frame(year=2005:2010),
                   'support')

# This form doesn't work.
dplyr::bind_rows(support, support)

# This form doesn't work.
dplyr::bind_rows(list(support, support))
```

To submit as sparklyr issue.

```{r printversion}
version
```


