---
output:
  md_document:
    variant: markdown_github
---

<!-- Generated from .Rmd. Please edit that file -->

## `dplyr` and `sparklyr`

Run CRAN version of `dplyr` and CRAN `sparklyr` as of 5-14-2017.

```{r CRANdplyr}
# devtools::install_github("tidyverse/dplyr")
# devtools::install_github('tidyverse/dbplyr')
# devtools::install_github('rstudio/sparklyr')
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
library('sparklyr')
packageVersion("sparklyr")
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
R.Version()$version.string
base::date()

sc <- sparklyr::spark_connect(version='2.0.2', 
   master = "local")
```

```{r joindups, error=TRUE}
d1 <- copy_to(sc, data.frame(x=1:3, y=4:6), 'd1',
              overwrite = TRUE)
d2 <- copy_to(sc, data.frame(x=1:3, y=7:9), 'd2',
              overwrite = TRUE)

left_join(d1, d2, by='x')
```

```{r rename, error=TRUE}
dLocal <- data.frame(x = 1:2,
                     origCol = c('a', 'b'),
                     stringsAsFactors = FALSE)

d <- copy_to(sc, dLocal, 'd',
             overwrite = TRUE)

# local
rename(dLocal, x2 = x, origCol2 = origCol)

# Spark
rename(d, x2 = x, origCol2 = origCol)
```


```{r cleanup}
spark_disconnect(sc)
rm(list=ls())
gc(verbose = FALSE)
```
