---
output:
  md_document:
    variant: markdown_github
---


```{r}
# 4-15-2017
# commit 58fcd949d7709b4be44e2789a1c5355a6bd148f3
# devtools::install_github("rstudio/sparklyr") 
# commit d7d2f10167b4ac919e876eb9a891fd53345be985
# devtools::install_github("tidyverse/dplyr")

library("sparklyr")
library("dplyr")
library("nycflights13")
sc <- spark_connect(version='2.0.2', master = "local")
flts <- dplyr::copy_to(sc, flights)
flts %>% mutate(zzz=1)  # works with dev version of Sparklyr
# used to fail 
#  https://github.com/tidyverse/dplyr/issues/2495
#  https://github.com/rstudio/sparklyr/issues/572 
#  https://github.com/rstudio/sparklyr/issues/577 
```

```{r versions}
packageVersion("sparklyr")
packageVersion("dplyr")
packageVersion("DBI")
```

```{r clean}
rm(list=ls())
gc()
```

Can only use dev/dev or CRAN/CRAN (can't seem to mix) right now:

With the dev version of dplyr installed (4/15/2017, 0.5.0.9002 commit d7d2f10) the CRAN version of sparklyr (4/15/2017, 0.5.3 ) will not load:

```r
library("sparklyr")
# Error : object 'sql_build' not found whilst loading namespace 'sparklyr'
# Error: package or namespace load failed for ‘sparklyr’
Problem goes away with dev-version of sparklyr (4/15/2017, 0.5.3-9005 commit 58fcd949d7709b4be44e2789a1c5355a6bd148f3).
```

https://github.com/rstudio/sparklyr/issues/623
https://github.com/tidyverse/dplyr/issues/2670
