---
output:
  md_document:
    variant: markdown_github
---

Factor with R data.frame.

<!-- Generated from .Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = " # "
)
options(width =100)
```


Some issues with `summarize_each` and factors.


```{r factorissue, error=TRUE}
library('dplyr')
R.Version()$version.string
packageVersion('dplyr')
d1 <- data.frame(y=c('a','b'),stringsAsFactors = FALSE)
d1 %>% dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
d2 <- data.frame(y=c('a','b'),stringsAsFactors = TRUE)
d2 %>% dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
```

Submitted as [dplyr issue 2269](https://github.com/hadley/dplyr/issues/2269).  Closed as "expected behavior" as this is what `min(factor(letters))` does.  That is a correct determination, but be aware many `dplyr` backends do support comparison, min, and max on characters types.

```{r factorissuedb, error=TRUE}
my_db <- dplyr::src_sqlite("replyr_sqliteEx.sqlite3", create = TRUE)
dplyr::copy_to(dest=my_db,df=d1,name='d1',overwrite=TRUE) %>% 
  dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
dplyr::copy_to(dest=my_db,df=d2,name='d2',overwrite=TRUE) %>% 
  dplyr::summarise_each(dplyr::funs(lexmin = min,lexmax = max))
```


```{r printversion}
version
```

