---
output:
  md_document:
    variant: markdown_github
---


<!-- Generated from .Rmd. Please edit that file -->

Non-`NA` numerics on left join with `sparklyr`.


```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = " # "
)
options(width =100)
```

```{r setup}
library('dplyr')
library('sparklyr')
sc <- sparklyr::spark_connect(version='2.0.0', 
                              master = "local")
```

```{r d1}
d1 <- data.frame(x= c('a','b','c'), 
                 y1 = c(10,2.5,1),
                 stringsAsFactors= FALSE)
d2 <- data.frame(x= c('a','c','d'), y2 = 1:3,
                 stringsAsFactors= FALSE)
d1s <- copy_to(sc, d1, overwrite = TRUE)
spark_write_parquet(d1s, 'd1s')
d2s <- copy_to(sc, d2, overwrite = TRUE)
spark_write_parquet(d2s, 'd2s')

d1s <- spark_read_parquet(sc, 'd1s', 'd1s', memory=FALSE, overwrite = TRUE)
d2s <- spark_read_parquet(sc, 'd2s', 'd2s', memory=FALSE, overwrite = TRUE)

d1s %>% 
  mutate(y1 = pmin(5,y1)) %>%
  left_join(d2s, by='x')
# seeing -9.22372e+18 instead of NA on client join data from gs:// parquet
# files, not seeing it here.
```


Submitted as [sparklyr issue ]().

```{r info}
R.Version()$version.string
packageVersion('dplyr')
packageVersion('sparklyr')
class(sc)
sc$spark_home
print(sc)
version
```


