---
output:
  md_document:
    variant: markdown_github
---

<!-- Generated from .Rmd. Please edit that file -->

## Sparklyr rename fails with dev version of dplyr

Rename fails in Sparklyr, think it depends on verison of dplyr.  Definitely seeing it in the dev version of dplyr as of 5-14-2017.  Confirmed it works properly for dplyr 0.5.0.

Submitted as [`Sparklyr` issue 678](https://github.com/rstudio/sparklyr/issues/678) and [`dplyr` issue 2776](https://github.com/tidyverse/dplyr/issues/2776).

```{r example, error = TRUE}
# devtools::install_github("tidyverse/dplyr")
# devtools::install_github('tidyverse/dbplyr')
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
library('sparklyr')
packageVersion("sparklyr")
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
R.Version()$version.string

dLocal <- data.frame(x = 1:2,
                     origCol = c('a', 'b'),
                     stringsAsFactors = FALSE)

sc <- sparklyr::spark_connect(version='2.0.2', 
   master = "local")

d <- copy_to(sc, dLocal, 'd')

# works
rename(dLocal, x2 = x, origCol2 = origCol)

# throws
rename(d, x2 = x, origCol2 = origCol)
```

```{r cleanup}
spark_disconnect(sc)
rm(list=ls())
gc(verbose = FALSE)
```
