---
title: "Why `reply`"
author: "John Mount"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

```{r loadpkgs}
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
packageVersion("dbplyr")
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
library("replyr")
packageVersion("replyr")
R.Version()$version.string
```

```{r unionall, error=TRUE}
my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
dr <- dplyr::copy_to(my_db,
                     data.frame(x= c(1,2),
                                y= c('a','b'),
                                stringsAsFactors = FALSE),
                     'dr',
                     overwrite=TRUE)
dr <- head(dr,1)

# works
replyr_union_all(dr, dr)

# throws
dplyr::union_all(dr, dr)
```

```{r rename, error=TRUE}
dLocal <- data.frame(x = 1:2,
                     origCol = c("a", "b"),
                     stringsAsFactors = FALSE)

sc <- sparklyr::spark_connect(version = "2.0.2",
                              master = "local")

d <- copy_to(sc, dLocal, "d")

# works
dLocal %>%
  rename(x2 = x, origCol2 = origCol)

# works
d %>%
  rename(x2 = x) %>%
  rename(origCol2 = origCol)

# works
d %>%
  replyr_mapRestrictCols(c("x2"="x", "origCol2"="origCol"))

# throws
d %>%
  rename(x2 = x, origCol2 = origCol)
```
